name: Paths

on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          root:
            - '.github/**'
          core:
            - 'src/components/**'

    # run only if 'backend' files were changed
    - name: frontend tests
      if: steps.filter.outputs.frontend == 'true'
      run: ...

    - name: print
      env:
        GITHUB_OUTPUTS: ${{ toJson(steps.filter.outputs.root_files) }}
      run: echo "$GITHUB_OUTPUTS"